name: Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Every six hours
    - cron: "0 */6 * * *"

  workflow_dispatch:
          
jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Curl
        run: sudo apt-get install libssl-dev libcurl4-openssl-dev
        
      - name: Run python scripts 
        working-directory: ./tools
        run: |
          pip install -r requirements.txt
          python3 scraper.py | python3 parser.py | python3 extractor.py "Armed attacks and conflicts" "Armed conflicts and attacks" | python3 locator.py | python3 jsonifier.py ../frontend/src/data/incidents.json

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install and build
        working-directory: ./frontend
        env:
          CI: false
        run: |
          npm install --build-from-source
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          cname: global-conflicts.com
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: Global-Conflicts/global-conflicts.github.io
          publish_branch: main
          publish_dir: ./frontend/dist
